//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("schoolModel", "FK__finance__std_id__023D5A04", "stdBasic", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(School.stdBasic), "finance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(School.finance), true)]

#endregion

namespace School
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class schoolEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new schoolEntities object using the connection string found in the 'schoolEntities' section of the application configuration file.
        /// </summary>
        public schoolEntities() : base("name=schoolEntities", "schoolEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new schoolEntities object.
        /// </summary>
        public schoolEntities(string connectionString) : base(connectionString, "schoolEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new schoolEntities object.
        /// </summary>
        public schoolEntities(EntityConnection connection) : base(connection, "schoolEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<finance> finances
        {
            get
            {
                if ((_finances == null))
                {
                    _finances = base.CreateObjectSet<finance>("finances");
                }
                return _finances;
            }
        }
        private ObjectSet<finance> _finances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stdBasic> stdBasics
        {
            get
            {
                if ((_stdBasics == null))
                {
                    _stdBasics = base.CreateObjectSet<stdBasic>("stdBasics");
                }
                return _stdBasics;
            }
        }
        private ObjectSet<stdBasic> _stdBasics;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the finances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofinances(finance finance)
        {
            base.AddObject("finances", finance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stdBasics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostdBasics(stdBasic stdBasic)
        {
            base.AddObject("stdBasics", stdBasic);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schoolModel", Name="finance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class finance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new finance object.
        /// </summary>
        /// <param name="std_id">Initial value of the std_id property.</param>
        /// <param name="std_name">Initial value of the std_name property.</param>
        public static finance Createfinance(global::System.Int32 std_id, global::System.String std_name)
        {
            finance finance = new finance();
            finance.std_id = std_id;
            finance.std_name = std_name;
            return finance;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 std_id
        {
            get
            {
                return _std_id;
            }
            set
            {
                if (_std_id != value)
                {
                    Onstd_idChanging(value);
                    ReportPropertyChanging("std_id");
                    _std_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("std_id");
                    Onstd_idChanged();
                }
            }
        }
        private global::System.Int32 _std_id;
        partial void Onstd_idChanging(global::System.Int32 value);
        partial void Onstd_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String account_no
        {
            get
            {
                return _account_no;
            }
            set
            {
                Onaccount_noChanging(value);
                ReportPropertyChanging("account_no");
                _account_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("account_no");
                Onaccount_noChanged();
            }
        }
        private global::System.String _account_no;
        partial void Onaccount_noChanging(global::System.String value);
        partial void Onaccount_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bank_name
        {
            get
            {
                return _bank_name;
            }
            set
            {
                Onbank_nameChanging(value);
                ReportPropertyChanging("bank_name");
                _bank_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bank_name");
                Onbank_nameChanged();
            }
        }
        private global::System.String _bank_name;
        partial void Onbank_nameChanging(global::System.String value);
        partial void Onbank_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String branch_code
        {
            get
            {
                return _branch_code;
            }
            set
            {
                Onbranch_codeChanging(value);
                ReportPropertyChanging("branch_code");
                _branch_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("branch_code");
                Onbranch_codeChanged();
            }
        }
        private global::System.String _branch_code;
        partial void Onbranch_codeChanging(global::System.String value);
        partial void Onbranch_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String std_name
        {
            get
            {
                return _std_name;
            }
            set
            {
                if (_std_name != value)
                {
                    Onstd_nameChanging(value);
                    ReportPropertyChanging("std_name");
                    _std_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("std_name");
                    Onstd_nameChanged();
                }
            }
        }
        private global::System.String _std_name;
        partial void Onstd_nameChanging(global::System.String value);
        partial void Onstd_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String std_class
        {
            get
            {
                return _std_class;
            }
            set
            {
                Onstd_classChanging(value);
                ReportPropertyChanging("std_class");
                _std_class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("std_class");
                Onstd_classChanged();
            }
        }
        private global::System.String _std_class;
        partial void Onstd_classChanging(global::System.String value);
        partial void Onstd_classChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String std_section
        {
            get
            {
                return _std_section;
            }
            set
            {
                Onstd_sectionChanging(value);
                ReportPropertyChanging("std_section");
                _std_section = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("std_section");
                Onstd_sectionChanged();
            }
        }
        private global::System.String _std_section;
        partial void Onstd_sectionChanging(global::System.String value);
        partial void Onstd_sectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String due_date
        {
            get
            {
                return _due_date;
            }
            set
            {
                Ondue_dateChanging(value);
                ReportPropertyChanging("due_date");
                _due_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("due_date");
                Ondue_dateChanged();
            }
        }
        private global::System.String _due_date;
        partial void Ondue_dateChanging(global::System.String value);
        partial void Ondue_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String validity_date
        {
            get
            {
                return _validity_date;
            }
            set
            {
                Onvalidity_dateChanging(value);
                ReportPropertyChanging("validity_date");
                _validity_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("validity_date");
                Onvalidity_dateChanged();
            }
        }
        private global::System.String _validity_date;
        partial void Onvalidity_dateChanging(global::System.String value);
        partial void Onvalidity_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String issue_date
        {
            get
            {
                return _issue_date;
            }
            set
            {
                Onissue_dateChanging(value);
                ReportPropertyChanging("issue_date");
                _issue_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("issue_date");
                Onissue_dateChanged();
            }
        }
        private global::System.String _issue_date;
        partial void Onissue_dateChanging(global::System.String value);
        partial void Onissue_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> registration_fee
        {
            get
            {
                return _registration_fee;
            }
            set
            {
                Onregistration_feeChanging(value);
                ReportPropertyChanging("registration_fee");
                _registration_fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("registration_fee");
                Onregistration_feeChanged();
            }
        }
        private Nullable<global::System.Decimal> _registration_fee;
        partial void Onregistration_feeChanging(Nullable<global::System.Decimal> value);
        partial void Onregistration_feeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> admission_fee
        {
            get
            {
                return _admission_fee;
            }
            set
            {
                Onadmission_feeChanging(value);
                ReportPropertyChanging("admission_fee");
                _admission_fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("admission_fee");
                Onadmission_feeChanged();
            }
        }
        private Nullable<global::System.Decimal> _admission_fee;
        partial void Onadmission_feeChanging(Nullable<global::System.Decimal> value);
        partial void Onadmission_feeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> security_deposit
        {
            get
            {
                return _security_deposit;
            }
            set
            {
                Onsecurity_depositChanging(value);
                ReportPropertyChanging("security_deposit");
                _security_deposit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("security_deposit");
                Onsecurity_depositChanged();
            }
        }
        private Nullable<global::System.Decimal> _security_deposit;
        partial void Onsecurity_depositChanging(Nullable<global::System.Decimal> value);
        partial void Onsecurity_depositChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> annual_charge
        {
            get
            {
                return _annual_charge;
            }
            set
            {
                Onannual_chargeChanging(value);
                ReportPropertyChanging("annual_charge");
                _annual_charge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("annual_charge");
                Onannual_chargeChanged();
            }
        }
        private Nullable<global::System.Decimal> _annual_charge;
        partial void Onannual_chargeChanging(Nullable<global::System.Decimal> value);
        partial void Onannual_chargeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> prospectus
        {
            get
            {
                return _prospectus;
            }
            set
            {
                OnprospectusChanging(value);
                ReportPropertyChanging("prospectus");
                _prospectus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prospectus");
                OnprospectusChanged();
            }
        }
        private Nullable<global::System.Decimal> _prospectus;
        partial void OnprospectusChanging(Nullable<global::System.Decimal> value);
        partial void OnprospectusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> tuition_fee
        {
            get
            {
                return _tuition_fee;
            }
            set
            {
                Ontuition_feeChanging(value);
                ReportPropertyChanging("tuition_fee");
                _tuition_fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tuition_fee");
                Ontuition_feeChanged();
            }
        }
        private Nullable<global::System.Decimal> _tuition_fee;
        partial void Ontuition_feeChanging(Nullable<global::System.Decimal> value);
        partial void Ontuition_feeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> computer_ict_fee
        {
            get
            {
                return _computer_ict_fee;
            }
            set
            {
                Oncomputer_ict_feeChanging(value);
                ReportPropertyChanging("computer_ict_fee");
                _computer_ict_fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("computer_ict_fee");
                Oncomputer_ict_feeChanged();
            }
        }
        private Nullable<global::System.Decimal> _computer_ict_fee;
        partial void Oncomputer_ict_feeChanging(Nullable<global::System.Decimal> value);
        partial void Oncomputer_ict_feeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> lab_charges
        {
            get
            {
                return _lab_charges;
            }
            set
            {
                Onlab_chargesChanging(value);
                ReportPropertyChanging("lab_charges");
                _lab_charges = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lab_charges");
                Onlab_chargesChanged();
            }
        }
        private Nullable<global::System.Decimal> _lab_charges;
        partial void Onlab_chargesChanging(Nullable<global::System.Decimal> value);
        partial void Onlab_chargesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> arrears
        {
            get
            {
                return _arrears;
            }
            set
            {
                OnarrearsChanging(value);
                ReportPropertyChanging("arrears");
                _arrears = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("arrears");
                OnarrearsChanged();
            }
        }
        private Nullable<global::System.Decimal> _arrears;
        partial void OnarrearsChanging(Nullable<global::System.Decimal> value);
        partial void OnarrearsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> safety_fee
        {
            get
            {
                return _safety_fee;
            }
            set
            {
                Onsafety_feeChanging(value);
                ReportPropertyChanging("safety_fee");
                _safety_fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("safety_fee");
                Onsafety_feeChanged();
            }
        }
        private Nullable<global::System.Decimal> _safety_fee;
        partial void Onsafety_feeChanging(Nullable<global::System.Decimal> value);
        partial void Onsafety_feeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> admission_process_fee
        {
            get
            {
                return _admission_process_fee;
            }
            set
            {
                Onadmission_process_feeChanging(value);
                ReportPropertyChanging("admission_process_fee");
                _admission_process_fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("admission_process_fee");
                Onadmission_process_feeChanged();
            }
        }
        private Nullable<global::System.Decimal> _admission_process_fee;
        partial void Onadmission_process_feeChanging(Nullable<global::System.Decimal> value);
        partial void Onadmission_process_feeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ict_book
        {
            get
            {
                return _ict_book;
            }
            set
            {
                Onict_bookChanging(value);
                ReportPropertyChanging("ict_book");
                _ict_book = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ict_book");
                Onict_bookChanged();
            }
        }
        private Nullable<global::System.Decimal> _ict_book;
        partial void Onict_bookChanging(Nullable<global::System.Decimal> value);
        partial void Onict_bookChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> uniform_fee
        {
            get
            {
                return _uniform_fee;
            }
            set
            {
                Onuniform_feeChanging(value);
                ReportPropertyChanging("uniform_fee");
                _uniform_fee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uniform_fee");
                Onuniform_feeChanged();
            }
        }
        private Nullable<global::System.Decimal> _uniform_fee;
        partial void Onuniform_feeChanging(Nullable<global::System.Decimal> value);
        partial void Onuniform_feeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> other
        {
            get
            {
                return _other;
            }
            set
            {
                OnotherChanging(value);
                ReportPropertyChanging("other");
                _other = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("other");
                OnotherChanged();
            }
        }
        private Nullable<global::System.Decimal> _other;
        partial void OnotherChanging(Nullable<global::System.Decimal> value);
        partial void OnotherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> fine
        {
            get
            {
                return _fine;
            }
            set
            {
                OnfineChanging(value);
                ReportPropertyChanging("fine");
                _fine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fine");
                OnfineChanged();
            }
        }
        private Nullable<global::System.Decimal> _fine;
        partial void OnfineChanging(Nullable<global::System.Decimal> value);
        partial void OnfineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> before_due_date
        {
            get
            {
                return _before_due_date;
            }
            set
            {
                Onbefore_due_dateChanging(value);
                ReportPropertyChanging("before_due_date");
                _before_due_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("before_due_date");
                Onbefore_due_dateChanged();
            }
        }
        private Nullable<global::System.Decimal> _before_due_date;
        partial void Onbefore_due_dateChanging(Nullable<global::System.Decimal> value);
        partial void Onbefore_due_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> after_due_date
        {
            get
            {
                return _after_due_date;
            }
            set
            {
                Onafter_due_dateChanging(value);
                ReportPropertyChanging("after_due_date");
                _after_due_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("after_due_date");
                Onafter_due_dateChanged();
            }
        }
        private Nullable<global::System.Decimal> _after_due_date;
        partial void Onafter_due_dateChanging(Nullable<global::System.Decimal> value);
        partial void Onafter_due_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schoolModel", "FK__finance__std_id__023D5A04", "stdBasic")]
        public stdBasic stdBasic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<stdBasic>("schoolModel.FK__finance__std_id__023D5A04", "stdBasic").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<stdBasic>("schoolModel.FK__finance__std_id__023D5A04", "stdBasic").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<stdBasic> stdBasicReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<stdBasic>("schoolModel.FK__finance__std_id__023D5A04", "stdBasic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<stdBasic>("schoolModel.FK__finance__std_id__023D5A04", "stdBasic", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="schoolModel", Name="stdBasic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stdBasic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stdBasic object.
        /// </summary>
        /// <param name="std_id">Initial value of the std_id property.</param>
        /// <param name="std_name">Initial value of the std_name property.</param>
        public static stdBasic CreatestdBasic(global::System.Int32 std_id, global::System.String std_name)
        {
            stdBasic stdBasic = new stdBasic();
            stdBasic.std_id = std_id;
            stdBasic.std_name = std_name;
            return stdBasic;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 std_id
        {
            get
            {
                return _std_id;
            }
            set
            {
                if (_std_id != value)
                {
                    Onstd_idChanging(value);
                    ReportPropertyChanging("std_id");
                    _std_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("std_id");
                    Onstd_idChanged();
                }
            }
        }
        private global::System.Int32 _std_id;
        partial void Onstd_idChanging(global::System.Int32 value);
        partial void Onstd_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String branch_code
        {
            get
            {
                return _branch_code;
            }
            set
            {
                Onbranch_codeChanging(value);
                ReportPropertyChanging("branch_code");
                _branch_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("branch_code");
                Onbranch_codeChanged();
            }
        }
        private global::System.String _branch_code;
        partial void Onbranch_codeChanging(global::System.String value);
        partial void Onbranch_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String std_web_portal_id
        {
            get
            {
                return _std_web_portal_id;
            }
            set
            {
                Onstd_web_portal_idChanging(value);
                ReportPropertyChanging("std_web_portal_id");
                _std_web_portal_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("std_web_portal_id");
                Onstd_web_portal_idChanged();
            }
        }
        private global::System.String _std_web_portal_id;
        partial void Onstd_web_portal_idChanging(global::System.String value);
        partial void Onstd_web_portal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String account_no
        {
            get
            {
                return _account_no;
            }
            set
            {
                Onaccount_noChanging(value);
                ReportPropertyChanging("account_no");
                _account_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("account_no");
                Onaccount_noChanged();
            }
        }
        private global::System.String _account_no;
        partial void Onaccount_noChanging(global::System.String value);
        partial void Onaccount_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bank_name
        {
            get
            {
                return _bank_name;
            }
            set
            {
                Onbank_nameChanging(value);
                ReportPropertyChanging("bank_name");
                _bank_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bank_name");
                Onbank_nameChanged();
            }
        }
        private global::System.String _bank_name;
        partial void Onbank_nameChanging(global::System.String value);
        partial void Onbank_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String std_name
        {
            get
            {
                return _std_name;
            }
            set
            {
                Onstd_nameChanging(value);
                ReportPropertyChanging("std_name");
                _std_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("std_name");
                Onstd_nameChanged();
            }
        }
        private global::System.String _std_name;
        partial void Onstd_nameChanging(global::System.String value);
        partial void Onstd_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String father_name
        {
            get
            {
                return _father_name;
            }
            set
            {
                Onfather_nameChanging(value);
                ReportPropertyChanging("father_name");
                _father_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("father_name");
                Onfather_nameChanged();
            }
        }
        private global::System.String _father_name;
        partial void Onfather_nameChanging(global::System.String value);
        partial void Onfather_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String std_address
        {
            get
            {
                return _std_address;
            }
            set
            {
                Onstd_addressChanging(value);
                ReportPropertyChanging("std_address");
                _std_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("std_address");
                Onstd_addressChanged();
            }
        }
        private global::System.String _std_address;
        partial void Onstd_addressChanging(global::System.String value);
        partial void Onstd_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String std_class
        {
            get
            {
                return _std_class;
            }
            set
            {
                Onstd_classChanging(value);
                ReportPropertyChanging("std_class");
                _std_class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("std_class");
                Onstd_classChanged();
            }
        }
        private global::System.String _std_class;
        partial void Onstd_classChanging(global::System.String value);
        partial void Onstd_classChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String std_section
        {
            get
            {
                return _std_section;
            }
            set
            {
                Onstd_sectionChanging(value);
                ReportPropertyChanging("std_section");
                _std_section = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("std_section");
                Onstd_sectionChanged();
            }
        }
        private global::System.String _std_section;
        partial void Onstd_sectionChanging(global::System.String value);
        partial void Onstd_sectionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("schoolModel", "FK__finance__std_id__023D5A04", "finance")]
        public EntityCollection<finance> finances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<finance>("schoolModel.FK__finance__std_id__023D5A04", "finance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<finance>("schoolModel.FK__finance__std_id__023D5A04", "finance", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
